In [ ]:
print("hello krish this side ")
print("did you play guitar")

hello krish this side 
did you play guitar


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


## introduction to tensor

In [ ]:
# scaller
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector =torch.tensor([3,4])
vector


tensor([3, 4])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX =torch.tensor([[7,5],[5,8]])
MATRIX

tensor([[7, 5],
        [5, 8]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([5, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR =torch.tensor([[[[1,2,3],
                      [4,5,6],
                       [9,8,6]]]])
TENSOR

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [9, 8, 6]]]])

In [ ]:
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0])
print(TENSOR.size)
print(type(TENSOR))

4
torch.Size([1, 1, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [9, 8, 6]]])
<built-in method size of Tensor object at 0x7c91471643c0>
<class 'torch.Tensor'>


##random tensor

In [ ]:
random_tensor = torch.rand(2,2,8)
random_tensor

tensor([[[0.2958, 0.6838, 0.1669, 0.1731, 0.4759, 0.3171, 0.1252, 0.7966],
         [0.9021, 0.5811, 0.4129, 0.0369, 0.3179, 0.6273, 0.7358, 0.4368]],

        [[0.3023, 0.7786, 0.1018, 0.8160, 0.3060, 0.5077, 0.4012, 0.5606],
         [0.3489, 0.8636, 0.4870, 0.8903, 0.9807, 0.2564, 0.1352, 0.9012]]])

In [ ]:
random_tensor.ndim

3

In [ ]:

#creating the random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(244,244,3))#height, width, color channnel
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

##tensor data type
###tensor data type is one of 3 big error you'll run into with pytorch and deep learning
###1tensor not right data type,shape,and not on the right device

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
flot_32_tensor = torch.tensor([3.0,6.0, 9.0],
                              dtype=None, # Setting data type to float32
                              device=None, # Setting device dynamically based on availability
                              requires_grad=False) # Explicitly setting requires_grad
flot_32_tensor
#what datatpyr of tensor (32 bit 64 bit 16bit floating point )
#used to precision computing

tensor([3., 6., 9.])

In [ ]:
flot_32_tensor.dtype

torch.float32

In [ ]:
flot_16_tensor = flot_32_tensor.type(torch.float16)


In [ ]:
flot_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
flot_16_tensor.dtype

torch.float16

In [ ]:
flot_16_tensor*flot_32_tensor

tensor([ 9., 36., 81.])

####differnt data type can mutiply bu some are show the error


In [ ]:
int_32_tensor = torch.tensor([3,6,9],
                             dtype=torch.long)



In [ ]:
int_32_tensor*flot_32_tensor

tensor([ 9., 36., 81.])

###getting info from the tensor
1 for data type -tensor.dtype
2.to get the shape-tensor.shape
3. to get the device innfo -tensor.device

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8172, 0.2409, 0.9980, 0.6119],
        [0.5617, 0.1943, 0.1411, 0.0905],
        [0.4218, 0.9529, 0.5288, 0.3354]])

In [ ]:
some_tensor.size(),some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
some_tensor.size()

torch.Size([3, 4])

## here we can  get the size of tensor with atribute(.shape) as well as the function (.size())

In [ ]:
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

tensor([[0.5611, 0.4375, 0.2005, 0.3933],
        [0.3970, 0.5699, 0.6058, 0.6529],
        [0.2191, 0.2404, 0.6206, 0.8178]])
torch.float32
torch.Size([3, 4])
cpu


# tensor operation


In [ ]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
torch.remainder(tensor,100)


tensor([1, 2, 3])

# matrix mutiplecation

In [ ]:
x = torch.rand(3,3)
x


tensor([[0.8772, 0.0265, 0.4565],
        [0.1935, 0.8667, 0.9997],
        [0.7845, 0.2030, 0.9463]])

In [ ]:
x*x


tensor([[[ 1,  4,  9],
         [16, 25, 36],
         [49, 64, 81]]])

In [ ]:
%%time
torch.matmul(x,x)

CPU times: user 0 ns, sys: 777 µs, total: 777 µs
Wall time: 1.72 ms


tensor([[[ 30,  36,  42],
         [ 66,  81,  96],
         [102, 126, 150]]])

In [ ]:
%%time
for i in range(len(x)):
  value = 0
  value +=tensor[i]*tensor[1]
  value


CPU times: user 707 µs, sys: 0 ns, total: 707 µs
Wall time: 544 µs


In [ ]:
# shape for matrix mutliplecation
tensor_A =torch.tensor([[1,2],
                        [2,3],
                        [4,5]])
tensor_B = torch.tensor([[7,10],
                         [5,6],
                         [8,9]])




In [ ]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

## transpose the matrix and then mutiply it  change the dimentions and get multiply

In [ ]:
transpose_B = tensor_B.T

In [ ]:
# the matrix mutiplication work whene we transpose the matrix because of the same of inner dimention rule in the matrix
# torch.mm and the torch.matmul both are use to mutiply the matrix
torch.matmul(tensor_A, transpose_B)

tensor([[27, 17, 26],
        [44, 28, 43],
        [78, 50, 77]])

## finding max min mean sum etc

In [ ]:

# creat the tensor
x = torch.arange(0 , 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the min value
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x),x.max(),x.dtype

(tensor(90), tensor(90), torch.int64)

# here the we have to change the dtype of x  for finding mean its  int type but it  takes float as the input

In [ ]:
# finding the mean
x.type(torch.float32).mean() , torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

In [ ]:
# sum
x.sum(), torch.sum(x)


(tensor(450), tensor(450))

#positional min and max


In [ ]:
# to find the postions of the max and min value argmin()/argmax functions are used
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin() ,torch.argmin(x)

(tensor(0), tensor(0))

In [ ]:
x.argmax(),torch.argmax(x)

(tensor(9), tensor(9))

### reshaping staking and squeezing and un squeezing

In [ ]:
x =torch.arange(1. , 10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# adding the extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z will also chnage the the x because they also share the same memory as the original
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stak tensor on top of each other
x_stacked = torch.stack([x,x,x], dim =0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

sqeez and unsqezz

In [ ]:
x = torch.zeros(2,1,2,1,2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [ ]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# indexing

In [ ]:
# indenxing in tensor is like in numpy indexing
x  = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# index on our new tensor
x[0][1][1]

tensor(5)

In [ ]:
x[:, 2,2]

tensor([9])

# numpy for pytorch


In [ ]:
# numpy arry to tensor
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #whene converting from the numpy -->pytorch its reflects the  default dtype of the array as float64
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor.dtype

torch.float64

In [ ]:
# change the array value
array = array + 1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor.dtype

torch.float32

#reproducbillity (trying to take random out of random)

* in short how neural network works learns:
start with randoms-->tensoroperation-->update random no. to try and make them better representation of the data -->again-->again-->again...

In [ ]:
### to reduce the randomnes in pytorch comes the concept of the **random seed** essentially WHAT THE RANDOM  seed does is "flavour" the randomness


In [ ]:
torch.rand(3,3)

tensor([[0.3053, 0.7880, 0.5946],
        [0.5565, 0.3890, 0.7036],
        [0.6397, 0.5033, 0.8871]])

In [ ]:
# creating 2 random tensor
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6637, 0.1728, 0.0643, 0.9611],
        [0.8888, 0.2376, 0.1879, 0.7239],
        [0.9754, 0.1792, 0.9237, 0.7222]])
tensor([[0.6018, 0.6997, 0.5384, 0.7142],
        [0.6419, 0.3352, 0.6965, 0.9962],
        [0.3102, 0.6832, 0.4684, 0.8148]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# lets make some random reproduceble tensor
# set the random seed
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_D =torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)
#

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
torch.manual_seed(random_seed)

## runnnign tensors and pytorch object on the gpu (and making faster computations)
* gpu - faster computation on numbers, thanks to cuda +Nvida Hardware +pytorch working behind the scences to make everything good

# check the gpu acces with pytorch


In [ ]:
# checkt the gpu conection
torch.cuda.is_available()

False

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
# setup device agnostic code
device ="cuda" if torch.cuda.is_available() else "cpu"
device


'cpu'

In [ ]:
# count no if device
torch.cuda.device_count()

0